---
- hosts: backup_servers

  tasks:
    - block:
        - name: "Check backup"
          ansible.builtin.include_tasks:
            file: ./tasks/check_borg_backup.yml
          loop: "{{ borg_repositories }}"
          vars:
            borg_repository_name: "{{ item.name }}"
            borg_repository_passphrase: "{{ item.passphrase }}"
            borg_repository_dump_path: "{{ item.sql_dump_folder_path | default(omit) }}"
          loop_control:
              label: "{{ item.name }}"
      rescue:
        - name: Send a mail on failure
          community.general.mail:
            host: "{{ mail_host }}"
            port: "{{ mail_port }}"
            password: "{{ mail_password }}"
            username: "{{ mail_from }}"
            from: "{{ mail_from }}"
            to: "{{ mail_to }}"
            subject: Some backup checks failed
            body: "Some backup checks failed. Check the playbook logs for more details."

        - name: Report failure
          ansible.builtin.fail:
            msg: "Some backup checks failed"
